### ISSUE TITLE
Doesn't compile on Ubuntu 14.04 with listed dependencies

### ISSUE THREAD

**Issue by joelhaasnoot** [hove-io/navitia#292]
With all the dependencies that are listed installed, getting this linker error at 48% of the compile:

/usr/bin/ld: CMakeFiles/osm2ed.dir/osm2ed.cpp.o: undefined reference to symbol 'inflate'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line

**Comment by koch-t** [comment]
Also: 
Linking CXX executable fare_integration_test
/usr/bin/ld: ../../type/libpb_lib.a(type.pb.cc.o): undefined reference to symbol 'pthread_once@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by antoine-de** [comment]
We usually build with gcc 4.7, and gcc 4.8 is a bit stricter.

Add the additional dependencies with PR #295
