### PR TITLE
Fix #292 part3

### LINKED ISSUE #292: Doesn't compile on Ubuntu 14.04 with listed dependencies
With all the dependencies that are listed installed, getting this linker error at 48% of the compile:

/usr/bin/ld: CMakeFiles/osm2ed.dir/osm2ed.cpp.o: undefined reference to symbol 'inflate'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line

### PR DESCRIPTION
**Pull request by koch-t**
These were also necessary for GCC 4.8
the package visu also had to be disabled, but i'm not sure if that's compiler related.

### CODE REVIEW

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by antoine-de** [comment]
Strange, worked well for us without that.

I'll try again as soon as possible.

Thanks for the patch again!

Jenkins, test this please.

**Comment by kinnou02** [comment]
For visu it's probably related to the dependence to marble. Anyway visu is not realy used.

ok to test.

**Comment by kinnou02** [comment]
ok to test.

**Comment by kinnou02** [comment]
Sorry for the spam, jenkins don't like commands with other messages.
Thanks for the patch.
