### PR TITLE
fix #292

### LINKED ISSUE #292: Doesn't compile on Ubuntu 14.04 with listed dependencies
With all the dependencies that are listed installed, getting this linker error at 48% of the compile:

/usr/bin/ld: CMakeFiles/osm2ed.dir/osm2ed.cpp.o: undefined reference to symbol 'inflate'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line

### PR DESCRIPTION
**Pull request by koch-t**

### CODE REVIEW

**Comment by stifoon** [comment]
Thanks, we're looking at this now.

Jenkins, test this please

**Comment by buildbotctp** [comment]
Can one of the admins verify this patch?

**Comment by antoine-de** [comment]
Sorry, we run navitia on ubuntu 12.04 and debian 7.

We're setting up an ubuntu 14.04 to test the installation.

Thanks for the quick fix !
